version: "3.8"

services:
#  postgres_db:
#    build: database/postgres
#    container_name: gym_postgresql_db
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: user_postgres
#      POSTGRES_PASSWORD: password_postgres
#      POSTGRES_DB: db_postgres
#    networks:
#      - gym_network

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - gym_network

networks:
  gym_network: {}