# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB db_postgres
ENV POSTGRES_USER user_postgres
ENV POSTGRES_PASSWORD password_postgres

# Expose the default PostgreSQL port (5432)
EXPOSE 5432